FROM node:20-alpine AS builder
WORKDIR /app
RUN npm install -g pnpm
COPY frontend/app/package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY frontend/app/. ./
RUN pnpm build

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/.next ./ ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
EXPOSE 3000
ENV NODE_ENV=production
CMD ["pnpm", "start"]
