FROM golang:1.23-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git gcc musl-dev

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/. ./
RUN CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -o aegisphish-backend cmd/main.go

FROM alpine:latest
WORKDIR /root/
RUN apk --no-cache add ca-certificates postgresql-client
COPY --from=builder /app/aegisphish-backend .
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 CMD wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1
CMD ["./aegisphish-backend"]
