apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aegisphish-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: aegisphish.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aegisphish-frontend
                port:
                  number: 3000
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: aegisphish-backend
                port:
                  number: 8080
